id: P009251
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG24847
  title: བརྡ་གསར་རྙིང་གི་ཁྱད་པར་སྟོན་པ་ལི་ཤིའི་གུར་ཁང་།
  author: ''
  volumes:
    a393faddd4cd4f04b663780373e3558a:
      image_group_id: I1KG24849
      title: ''
      volume_number: 1
      total_pages: 96
      base_file: v001.txt
