id: I76A69A44
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T23:46:16+00:00'
last_modified: '2022-06-08T09:41:39.670699+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24847
  title: བརྡ་གསར་རྙིང་གི་ཁྱད་པར་སྟོན་པ་ལི་ཤིའི་གུར་ཁང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FD0A:
      image_group_id: I1KG24849
      title: ''
      total_pages: 96
      order: 1
      base_file: FD0A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
